risky: true

preset: psr2

enabled:
  - alpha_ordered_imports
  - blank_line_after_opening_tag
  - cast_spaces
  - concat_with_spaces
  - native_function_casing
  - no_alias_functions
  - no_blank_lines_after_class_opening
  - no_leading_import_slash
  - no_unused_imports
  - no_whitespace_in_blank_line
  - phpdoc_no_access
  - self_accessor
  - short_array_syntax

finder:
  exclude:
    - "tests"
  name:
    - "*.php"
    - "*.php.dist"
  path:
    - "."
  not-path:
    - "resources/templates"
    - "resources/html"
