language: php

php:
  - 5.6
  - 7.0
  - nightly

sudo: false

cache:
  directories:
    - vendor

matrix:
  allow_failures:
    - php: nightly

env:
  matrix:
    - COMPOSER_PREFER="--prefer-stable"
    - COMPOSER_PREFER="--prefer-lowest"

before_script:
  - php -v
  - composer update $COMPOSER_PREFER

script:
  - vendor/bin/atoum --test-ext -p 'php -n -ddate.timezone=UTC'
